version: '3.4'

services:
    gymjournal.API:
        image: ${DOCKER_REGISTRY-}gymjournalapi
        build:
            context: .
            dockerfile: GymJournal.API/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - database

    database:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: "database"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"